### ISSUE TITLE
Moving Thespian into mbraceprojects

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/Thespian#7]
Hi @palladin @anirothan 

Thespian is a part of MBrace, and is also used for testing Vagabond.  Could we more the project to http://github.com/mbracepojects please?  That seems to be the logical home for it.

We need to make some updates to it - minor stuff related to updating FsPickler - and republish it.   

Thanks
Don

**Comment by dsyme** [comment]
The immediate problem is that Thespian depends on FsPickler 3.0 and we need to update to later versions of FsPickler https://github.com/nessos/Thespian/blob/master/paket.lock#L5

**Comment by dsyme** [comment]
@anirothan @palladin You have access, so you can just transfer the repository across I believe.  Would be very grateful if you could, thanks

**Comment by palladin** [comment]
Done!

**Comment by dsyme** [comment]
Thanks!
